### ISSUE TITLE
Concurrent calls to Do() with the same Client sometimes panic()

### ISSUE THREAD

**Issue by dgpc** [google/google-api-go-client#180]
Concurrent requests to a bigquery JobsService are crashing due to a concurrent map read and write. Are clients not expected to be goroutine-safe? If they are, I think this is a bug in the way URL parameters are being built in Do().

Apologies for the 84 line example, but this is as concise as I could make it whilst still being representative of what's going on:

```
package main

import (
	"flag"
	"fmt"
	"io/ioutil"
	"path"
	"path/filepath"
	"strings"
	"sync"
	"time"

	bigquery "google.golang.org/api/bigquery/v2"

	"golang.org/x/net/context"
	"golang.org/x/oauth2/google"
)

var project = flag.String("project", "", "GCP Project to use")
var dataset = flag.String("dataset", "", "Bigquery Dataset to use")
var dryRun = flag.Bool("dry_run", true, "Whether to run queries in dry-run mode")
var queryFiles = flag.String("query_files", "", "Files with SQL queries to run (comma-separated)")
var numParallelRuns = flag.Int("num_parallel_runs", 1, "Number of instances of each query to run in parallel")

func main() {
	flag.Parse()
	ctx := context.Background()
	cli, _ := google.DefaultClient(ctx, bigquery.BigqueryScope)
	bigqueryService, _ := bigquery.New(cli)
	jobsService := bigquery.NewJobsService(bigqueryService)

	queries := make(map[string]*bigquery.JobsQueryCall)
	jobIDs := make(map[string][]string)
	f := false
	for _, file := range strings.Split(*queryFiles, ",") {
		queryName := path.Base(file)
		queryName = queryName[0 : len(queryName)-len(filepath.Ext(queryName))]
		sqlStatement, err := ioutil.ReadFile(file)
		if err != nil {
			panic(err)
		}
		q := &bigquery.QueryRequest{
			DefaultDataset: &bigquery.DatasetReference{
				DatasetId: *dataset,
			},
			DryRun:        *dryRun,
			Query:         string(sqlStatement),
			TimeoutMs:     120000,
			UseLegacySql:  &f,
			UseQueryCache: &f,
		}
		queries[queryName] = jobsService.Query(*project, q)
		jobIDs[queryName] = make([]string, *numParallelRuns)
	}

	var wg sync.WaitGroup
	totalStart := time.Now()
	fmt.Println("Start:     ", totalStart.Format(time.RFC3339Nano))
	for name, q := range queries {
		for i := 0; i < *numParallelRuns; i++ {
			wg.Add(1)
			go func(name string, i int, q *bigquery.JobsQueryCall) {
				defer wg.Done()
				resp, err := q.Do()
				if err != nil {
					panic(err)
				}
				jobIDs[name][i] = resp.JobReference.JobId
			}(name, i, q)
		}
	}
	wg.Wait()
	fmt.Println("End:       ", time.Now().Format(time.RFC3339Nano))
	totalTime := time.Now().Sub(totalStart)
	fmt.Printf("Total Time: %.2f\n", totalTime.Seconds())
	for name, _ := range queries {
		fmt.Printf("Job IDs (%s): %s\n", name, strings.Join(jobIDs[name], ", "))
	}
}
```

This is results in panics fairly consistently once -num_parallel_runs is greater than 12, at which point we have multiple Do() calls on the same client being executed:

```
$ ./bq -query_files=query.sql -num_parallel_runs=12 -project=$PROJ -dataset=$DSET
Start:      2016-12-06T23:57:59.642062557Z
fatal error: concurrent map writes

goroutine 12 [running]:
runtime.throw(0x85c137, 0x15)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42023bcd8 sp=0xc42023bcb8
runtime.mapassign1(0x805a80, 0xc4201649f0, 0xc42023be70, 0xc42023be80)
	/usr/local/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc42023bdc0 sp=0xc42023bcd8
vendor/google.golang.org/api/bigquery/v2.(*JobsQueryCall).doRequest(0xc42001d900, 0x851d97, 0x4, 0x0, 0x402005, 0xc42019a740)
	/home/dgc/analytics/go/src/vendor/google.golang.org/api/bigquery/v2/bigquery-gen.go:4862 +0x1ff fp=0xc42023bea8 sp=0xc42023bdc0
vendor/google.golang.org/api/bigquery/v2.(*JobsQueryCall).Do(0xc42001d900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dgc/analytics/go/src/vendor/google.golang.org/api/bigquery/v2/bigquery-gen.go:4882 +0xa1 fp=0xc42023bf20 sp=0xc42023bea8
main.main.func1(0xc42018c510, 0xc4201649c0, 0x7ffff4626681, 0x3, 0x6, 0xc42001d900)
	/home/dgc/analytics/go/src/perf/crasher/crasher.go:70 +0x76 fp=0xc42023bf70 sp=0xc42023bf20
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42023bf78 sp=0xc42023bf70
created by main.main
	/home/dgc/analytics/go/src/perf/crasher/crasher.go:75 +0x934
```

**Comment by broady** [comment]
yes, clients (`FooService`) should be threadsafe.

/cc @bradfitz @jba

**Comment by dgpc** [comment]
Thanks @broady!
I am working around this for now by calling `runtime.GOMAXPROCS(1)` at the start of my main().

**Comment by broady** [comment]
I do see a race in your code, though. The assignment to `jobIDs[name][i]` is not behind a barrier.

**Comment by dgpc** [comment]
Those slices are sized according to the number of concurrent writers, and each goroutine writes to a single, unique element.

**Comment by broady** [comment]
Oh, right, I see what the code is doing. It's running the same call multiple times.

Calls should only be run once (though they can currently be run several times not in parallel).

**Comment by dgpc** [comment]
Gotcha. Service is goroutine-safe but JobsQueryCall is not. I'll create a separate Call for each of the concurrent runs.

Re: using `cloud.google.com/go/bigquery` instead of `google.golang.org/api/bigquery/v2`, I had started with the former but switched to the latter because of some other issues (notably performance when iterating through result rows, and output formatting). Maybe I'll give it another go later in the week and open issues if I can't get to the bottom of them. Thanks!

**Comment by broady** [comment]
Please do! We're nearing labeling it "beta", so any testing you can do against it ASAP means we could possibly incorporate the feedback.

**Comment by jba** [comment]
Hey David! I'm working hard on cloud.google.com/go/bigquery now. I wasn't aware of the performance issue with result iteration. Can you point me to something that's slow?

**Comment by dgpc** [comment]
Hi Jonathan! 

It seems to me the old API will block when you call `.Do()` on a query until results are ready (if the output is sufficiently small), and those results are included in the response object, whereas `.Read()` on a query in the new API just starts the job, then the row iterator is what's actually retrieving the results. The latter is slightly less convenient for benchmarking, since we have to iterate through the rows even if we don't want to print them out to get total time, but it's not too big a deal.

I've written a program (see bottom of this comment) that runs a query with both APIs and compares wall-clock time from the client for both running the query and printing the results. This seems to work fine with some queries:

$ ./apicompare -query_file=q1.sql
Query took 6.245636221s using api/bigquery/v2
<snip>
Printing output took 47.551µs using api/bigquery/v2
Total duration: 6.245683772s

Query took 786.140134ms using cloud/go/bigquery
<snip>
Printing output took 7.604723456s using cloud/go/bigquery
Total duration: 8.39086359s

In this case, the output is what I expect in both cases, and the new API took slightly longer to return results. That said, there is a fair bit of variation, and sometimes the new api is faster than the old one, so perhaps blaming the API is a red-herring.

More concerning, though, is this query:

```
SELECT DATE(TIMESTAMP_SECONDS(_time), "America/Los_Angeles") AS day, count(*) AS event_cnt
FROM `event_*`
WHERE _time >= UNIX_SECONDS(TIMESTAMP ("2016-10-01", "America/Los_Angeles"))
AND  _time <= UNIX_SECONDS(TIMESTAMP ("2016-10-30", "America/Los_Angeles")) + 86400
GROUP BY 1
ORDER BY 1
```

Which gives me:

```Query took 30.159219502s using api/bigquery/v2
2016-10-01 28897889
2016-10-02 30611543
2016-10-03 32961225
<... etc, more valid output here>
Printing output took 55.242µs using api/bigquery/v2
Total duration: 30.159274744s

Query took 1.158578824s using cloud/go/bigquery
panic: unrecognized type

goroutine 1 [running]:
panic(0x7e83e0, 0xc4203e5a30)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/home/dgc/analytics/go/src/perf/apicompare/bq.go:89 +0xc50
```

We get this `unrecognized type` error from the iterator. I'm using the iterator the way described in the doc example here:
https://godoc.org/cloud.google.com/go/bigquery#RowIterator

bq.go:
```package main

import (
	"flag"
	"fmt"
	"io/ioutil"
	"time"

	"cloud.google.com/go/bigquery"
	bqv2 "google.golang.org/api/bigquery/v2"
	"google.golang.org/api/iterator"

	"golang.org/x/net/context"
	"golang.org/x/oauth2/google"
)

var project = flag.String("project", "mixpanel-dev-1", "GCP Project to use")
var dataset = flag.String("dataset", "perf_2b", "Bigquery Dataset to use")
var queryFile = flag.String("query_file", "", "File with SQL query to run")

func main() {
	flag.Parse()
	ctx := context.Background()
	googleCli, err := google.DefaultClient(ctx, bqv2.BigqueryScope)
	if err != nil {
		panic(err)
	}
	bigqueryService, err := bqv2.New(googleCli)
	if err != nil {
		panic(err)
	}
	jobsService := bqv2.NewJobsService(bigqueryService)
	f := false
	sqlStatement, err := ioutil.ReadFile(*queryFile)
	if err != nil {
		panic(err)
	}
	q1 := jobsService.Query(*project, &bqv2.QueryRequest{
		DefaultDataset: &bqv2.DatasetReference{
			DatasetId: *dataset,
		},
		Query:         string(sqlStatement),
		TimeoutMs:     6000000,
		UseLegacySql:  &f,
		UseQueryCache: &f,
	})

	start := time.Now()
	resp, err := q1.Do()
	if err != nil {
		panic(err)
	}
	if !resp.JobComplete {
		panic("Query did not complete")
	}
	queryDuration := time.Since(start)
	fmt.Printf("Query took %v using api/bigquery/v2\n", queryDuration)
	start = time.Now()
	for _, row := range resp.Rows {
		for _, cell := range row.F {
			fmt.Printf("%v ", cell.V)
		}
		fmt.Println("")
	}
	outputDuration := time.Since(start)
	fmt.Printf("Printing output took %v using api/bigquery/v2\n", outputDuration)
	fmt.Printf("Total duration: %v\n\n", queryDuration+outputDuration)

	bigqueryCli, err := bigquery.NewClient(ctx, *project)
	start = time.Now()
	q2 := bigqueryCli.Query(string(sqlStatement))
	q2.QueryConfig.DefaultDatasetID = *dataset
	q2.QueryConfig.UseStandardSQL = true
	q2.QueryConfig.DisableQueryCache = true
	rows, err := q2.Read(ctx)
	if err != nil {
		panic(err)
	}
	queryDuration = time.Since(start)
	fmt.Printf("Query took %v using cloud/go/bigquery\n", queryDuration)
	start = time.Now()
	for {
		var row []bigquery.Value
		err := rows.Next(&row)
		if err == iterator.Done {
			break
		}
		if err != nil {
			panic(err)
		}
		fmt.Println(row)
	}
	outputDuration = time.Since(start)
	fmt.Printf("Printing output took %v using cloud/go/bigquery\n", outputDuration)
	fmt.Printf("Total duration: %v\n\n", queryDuration+outputDuration)
}```

Thanks for taking a look @jba!

**Comment by dgpc** [comment]
I'm afraid I'm no longer at the company that was using this client library.. Not sure if this is something @i0exception still cares about?
