### ISSUE TITLE
Some tagmanager paths cause panics

### ISSUE THREAD

**Issue by robbiet480** [google/google-api-go-client#269]
Functions such as `AccountsContainersWorkspacesService.Sync`, `AccountsContainersWorkspacesService.CreateVersion`, `AccountsContainersEnvironmentsService.Reauthorize` and a few others (full list at bottom of this issue) have paths formatted like `{+path}:sync`, `{+path}:create_version`, etc. When attempting to call these functions via this library, a panic occurs because `net/url` doesn't accept these kinds of paths as valid, thus causing the output of `url.Parse` on the relative paths to be nil, but without an error catch.

Here's the stacktrace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11755b6]

goroutine 1 [running]:
net/url.(*URL).ResolveReference(0xc42041a000, 0x0, 0x3)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/url/url.go:939 +0x36
google.golang.org/api/googleapi.ResolveRelative(0x1520324, 0x29, 0x1516a97, 0x16, 0xc4201ac1e8, 0x0)
	/Users/robbiet480/go/src/google.golang.org/api/googleapi/googleapi.go:275 +0x154
google.golang.org/api/tagmanager/v2.(*AccountsContainersWorkspacesCreateVersionCall).doRequest(0xc42047bae8, 0x150c0ec, 0x4, 0x0, 0xc42046f7f0, 0x1012ad8)
	/Users/robbiet480/go/src/google.golang.org/api/tagmanager/v2/tagmanager-gen.go:6681 +0x332
google.golang.org/api/tagmanager/v2.(*AccountsContainersWorkspacesCreateVersionCall).Do(0xc42046fae8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/robbiet480/go/src/google.golang.org/api/tagmanager/v2/tagmanager-gen.go:6700 +0x98
github.com/Bloomjoy/tagmanager_mgmt/cmd.glob..func1(0x1796060, 0x17bc610, 0x0, 0x0)
	/Users/robbiet480/go/src/github.com/Bloomjoy/tagmanager_mgmt/cmd/setIAVariableDefault.go:109 +0xcc3
github.com/spf13/cobra.(*Command).execute(0x1796060, 0x17bc610, 0x0, 0x0, 0x1796060, 0x17bc610)
	/Users/robbiet480/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x1795e00, 0x1796060, 0xc420096400, 0x1795f50)
	/Users/robbiet480/go/src/github.com/spf13/cobra/command.go:852 +0x334
github.com/spf13/cobra.(*Command).Execute(0x1795e00, 0x0, 0xc420131f48)
	/Users/robbiet480/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/Bloomjoy/tagmanager_mgmt/cmd.Execute()
	/Users/robbiet480/go/src/github.com/Bloomjoy/tagmanager_mgmt/cmd/root.go:46 +0x31
main.main()
	/Users/robbiet480/go/src/github.com/Bloomjoy/tagmanager_mgmt/main.go:20 +0x20
exit status 2
```

Not exactly sure how to fix this in the library without re-implementing the `googleapi.ResolveRelative` function entirely to not use `url.Parse` for these functions. Also, just a friendly note that I'm only using the tagmanager API, any other APIs with similarly formatted paths would probably cause the panic too.

Full list of affected paths:

```
{+path}:create_version
{+path}:entities
{+path}:move_entities_to_folder
{+path}:publish
{+path}:quick_preview
{+path}:reauthorize
{+path}:resolve_conflict
{+path}:revert
{+path}:set_latest
{+path}:sync
{+path}:undelete
```

**Comment by jba** [comment]
Thanks for the diagnosis. 

I think we should preprocess the relative URL in `googleapi.ResolveRelative` to remove everything after the last colon, then put it back after calling `url.ResolveReference`.

**Comment by jba** [comment]
See https://code-review.googlesource.com/c/google-api-go-client/+/27990
